### ISSUE TITLE
Lorenzo Starting Point

### ISSUE THREAD

**Issue by grammaton** [uniroma2/AEM-CR-HOA-2016#2]
@lolloferri92
- clone the repo
- download hoalibrary
- update readme with v0.1 targets

**Comment by grammaton** [comment]
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by lolloferri92** [comment]
- [x] clone the repo
- [ ] download hoalibrary
  - website offline
- [x] update readme with v0.1 targets
